// <auto-generated />
using System;
using DochazkaAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DochazkaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220707124838_M2")]
    partial class M2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DochazkaAPI.Models.Auto", b =>
                {
                    b.Property<short>("IdAuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdAuta"), 1L, 1);

                    b.Property<string>("Barva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Benzin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Maxpocmist")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Platnostccs")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Spotreba")
                        .HasColumnType("float");

                    b.Property<string>("Spz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Techkontr")
                        .HasColumnType("datetime2");

                    b.Property<string>("Techstav")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typauta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vyrazeno")
                        .HasColumnType("bit");

                    b.HasKey("IdAuta");

                    b.ToTable("Auta");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Dochazka", b =>
                {
                    b.Property<int>("IdDoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoch"), 1L, 1);

                    b.Property<short>("IdOdbor")
                        .HasColumnType("smallint");

                    b.Property<short>("IdUdalosti")
                        .HasColumnType("smallint");

                    b.Property<short>("IdZam")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Konec")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Kvedkon")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Kvedzac")
                        .HasColumnType("tinyint");

                    b.Property<double?>("Pocpracdnu")
                        .HasColumnType("float");

                    b.Property<DateTime?>("RecKon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RecZac")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Zacatek")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDoch");

                    b.HasIndex("IdUdalosti");

                    b.HasIndex("IdZam");

                    b.ToTable("Dochazka");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Odbor", b =>
                {
                    b.Property<short>("IdOdbor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdOdbor"), 1L, 1);

                    b.Property<string>("NazevOd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZkrOd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOdbor");

                    b.ToTable("Odbory");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Parametry", b =>
                {
                    b.Property<short>("IdParam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdParam"), 1L, 1);

                    b.Property<short>("DelObed")
                        .HasColumnType("smallint");

                    b.Property<short>("IdObed")
                        .HasColumnType("smallint");

                    b.Property<short>("IdPd")
                        .HasColumnType("smallint");

                    b.Property<short>("KorekceKonec")
                        .HasColumnType("smallint");

                    b.Property<short>("KorekceZacatek")
                        .HasColumnType("smallint");

                    b.Property<string>("MinZacPdGt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazevorg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("RefreshInt")
                        .HasColumnType("smallint");

                    b.Property<string>("TsUstredna")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdParam");

                    b.ToTable("Parametry");
                });

            modelBuilder.Entity("DochazkaAPI.Models.PracdenRok", b =>
                {
                    b.Property<int>("PracDenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PracDenId"), 1L, 1);

                    b.Property<int>("Mes01")
                        .HasColumnType("int");

                    b.Property<int>("Mes02")
                        .HasColumnType("int");

                    b.Property<int>("Mes03")
                        .HasColumnType("int");

                    b.Property<int>("Mes04")
                        .HasColumnType("int");

                    b.Property<int>("Mes05")
                        .HasColumnType("int");

                    b.Property<int>("Mes06")
                        .HasColumnType("int");

                    b.Property<int>("Mes07")
                        .HasColumnType("int");

                    b.Property<int>("Mes08")
                        .HasColumnType("int");

                    b.Property<int>("Mes09")
                        .HasColumnType("int");

                    b.Property<int>("Mes10")
                        .HasColumnType("int");

                    b.Property<int>("Mes11")
                        .HasColumnType("int");

                    b.Property<int>("Mes12")
                        .HasColumnType("int");

                    b.Property<int>("Rok")
                        .HasColumnType("int");

                    b.HasKey("PracDenId");

                    b.ToTable("Pracdny");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Rezauta", b =>
                {
                    b.Property<int>("IdRezerv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRezerv"), 1L, 1);

                    b.Property<string>("Cesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Dulezitost")
                        .HasColumnType("tinyint");

                    b.Property<string>("Duvod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("IdAuta")
                        .HasColumnType("smallint");

                    b.Property<short>("IdOdbor")
                        .HasColumnType("smallint");

                    b.Property<int>("IdRidic")
                        .HasColumnType("int");

                    b.Property<int>("IdSpolc1")
                        .HasColumnType("int");

                    b.Property<int>("IdSpolc2")
                        .HasColumnType("int");

                    b.Property<int>("IdSpolc3")
                        .HasColumnType("int");

                    b.Property<int>("IdSpolc4")
                        .HasColumnType("int");

                    b.Property<int>("IdSpolc5")
                        .HasColumnType("int");

                    b.Property<short>("IdZam")
                        .HasColumnType("smallint");

                    b.Property<bool>("OdpRead")
                        .HasColumnType("bit");

                    b.Property<string>("Pozadavky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poznamky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RezervDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RezervOd")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Stavrez")
                        .HasColumnType("tinyint");

                    b.Property<bool>("ZamDele")
                        .HasColumnType("bit");

                    b.Property<bool>("Zmenaterm")
                        .HasColumnType("bit");

                    b.HasKey("IdRezerv");

                    b.HasIndex("IdAuta");

                    b.HasIndex("IdZam");

                    b.ToTable("Rezaut");
                });

            modelBuilder.Entity("DochazkaAPI.Models.RoleZamestnanec", b =>
                {
                    b.Property<int>("IdRoleZam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoleZam"), 1L, 1);

                    b.Property<int>("Agenda")
                        .HasColumnType("int");

                    b.Property<short>("IdZam")
                        .HasColumnType("smallint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("VychoziRole")
                        .HasColumnType("bit");

                    b.HasKey("IdRoleZam");

                    b.HasIndex("IdZam");

                    b.ToTable("RoleZamestnancu");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Svatek", b =>
                {
                    b.Property<short>("IdSvatku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdSvatku"), 1L, 1);

                    b.Property<DateTime>("DatSvat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazSvat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSvatku");

                    b.ToTable("Svatky");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Udalost", b =>
                {
                    b.Property<short>("IdUdalosti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdUdalosti"), 1L, 1);

                    b.Property<bool>("CasIn")
                        .HasColumnType("bit");

                    b.Property<bool>("DatumIn")
                        .HasColumnType("bit");

                    b.Property<bool?>("DnyIn")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCas")
                        .HasColumnType("int");

                    b.Property<double>("MaxDny")
                        .HasColumnType("float");

                    b.Property<short>("MaxOpak")
                        .HasColumnType("smallint");

                    b.Property<int?>("MinCas")
                        .HasColumnType("int");

                    b.Property<double>("MinDny")
                        .HasColumnType("float");

                    b.Property<string>("Nazev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prepovol")
                        .HasColumnType("bit");

                    b.Property<bool>("Preruseni")
                        .HasColumnType("bit");

                    b.Property<bool>("System")
                        .HasColumnType("bit");

                    b.Property<short>("TypuTisk")
                        .HasColumnType("smallint");

                    b.Property<short>("VypObedy")
                        .HasColumnType("smallint");

                    b.Property<short>("VypPracdoby")
                        .HasColumnType("smallint");

                    b.Property<string>("Vysvetlivky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Zakladni")
                        .HasColumnType("bit");

                    b.Property<string>("ZkrUdal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUdalosti");

                    b.ToTable("Udalosti");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Zamestnanec", b =>
                {
                    b.Property<short>("IdZam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdZam"), 1L, 1);

                    b.Property<double>("Denuvazek")
                        .HasColumnType("float");

                    b.Property<string>("DomenaPrihlasovaciJmeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IdOdbor")
                        .HasColumnType("smallint");

                    b.Property<string>("Jmeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Mesuvazek")
                        .HasColumnType("float");

                    b.Property<bool?>("NevkladatPauzuObed")
                        .HasColumnType("bit");

                    b.Property<bool?>("NezkracovatPriViceHod")
                        .HasColumnType("bit");

                    b.Property<bool?>("NezobrazVNepritomnosti")
                        .HasColumnType("bit");

                    b.Property<string>("Prijmeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TsDaktmob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TsDaktpev")
                        .HasColumnType("datetime2");

                    b.Property<string>("TsEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TsMobil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TsPevna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vyrazen")
                        .HasColumnType("bit");

                    b.Property<bool?>("ZobrazVKontPritom")
                        .HasColumnType("bit");

                    b.HasKey("IdZam");

                    b.HasIndex("IdOdbor");

                    b.ToTable("Zamestnanci");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Dochazka", b =>
                {
                    b.HasOne("DochazkaAPI.Models.Udalost", "Udalost")
                        .WithMany("Dochazka")
                        .HasForeignKey("IdUdalosti")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DochazkaAPI.Models.Zamestnanec", "Id")
                        .WithMany("Dochazka")
                        .HasForeignKey("IdZam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Id");

                    b.Navigation("Udalost");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Rezauta", b =>
                {
                    b.HasOne("DochazkaAPI.Models.Auto", "Auto")
                        .WithMany("Rezaut")
                        .HasForeignKey("IdAuta");

                    b.HasOne("DochazkaAPI.Models.Zamestnanec", "Zamestnanec")
                        .WithMany("Rezaut")
                        .HasForeignKey("IdZam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auto");

                    b.Navigation("Zamestnanec");
                });

            modelBuilder.Entity("DochazkaAPI.Models.RoleZamestnanec", b =>
                {
                    b.HasOne("DochazkaAPI.Models.Zamestnanec", "Zamestnanec")
                        .WithMany()
                        .HasForeignKey("IdZam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zamestnanec");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Zamestnanec", b =>
                {
                    b.HasOne("DochazkaAPI.Models.Odbor", "Odbor")
                        .WithMany("Zamestnanci")
                        .HasForeignKey("IdOdbor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odbor");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Auto", b =>
                {
                    b.Navigation("Rezaut");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Odbor", b =>
                {
                    b.Navigation("Zamestnanci");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Udalost", b =>
                {
                    b.Navigation("Dochazka");
                });

            modelBuilder.Entity("DochazkaAPI.Models.Zamestnanec", b =>
                {
                    b.Navigation("Dochazka");

                    b.Navigation("Rezaut");
                });
#pragma warning restore 612, 618
        }
    }
}
